runtime: go116  # or another supported version

instance_class: F1

env_variables:
  BUCKET_NAME: "example-gcs-bucket"

handlers:
- url: /.*
  static_dir: static
  secure: always
  redirect_http_response_code: 301
